//! Config — .prompt-lens.yaml file handling.

use std::path::Path;

pub fn init_config(force: bool) {
    let cfg_path = Path::new(".prompt-lens.yaml");

    if cfg_path.exists() && !force {
        eprintln!("Error: .prompt-lens.yaml already exists. Use --force to overwrite.");
        std::process::exit(1);
    }

    let config = r#"# prompt-lens configuration
# Generated by: prompt-lens init

# Default model for cost calculation
default_model: claude-3-5-sonnet

# Output theme: ansi | nocolor | json
theme: ansi

# Custom optimization rules (optional)
# verbose_phrases:
#   - from: "please kindly"
#     to: "please"

# Suppress warnings for specific patterns (optional)
# ignore_patterns:
#   - "^\\[AUTO-GEN\\]"
"#;

    std::fs::write(cfg_path, config).expect("Failed to write config file");
    println!("[prompt-lens] Config file created: {}", cfg_path.display());
    println!("[prompt-lens] Edit .prompt-lens.yaml to customize settings.");
}

#[allow(dead_code)]
pub fn load_config() -> Option<serde_yaml::Value> {
    let cfg_path = Path::new(".prompt-lens.yaml");
    if cfg_path.exists() {
        let content = std::fs::read_to_string(cfg_path).ok()?;
        serde_yaml::from_str(&content).ok()
    } else {
        None
    }
}