//! Config — .prompt-lens.yaml file handling.

use std::path::Path;

pub fn init_config(force: bool) {
    let cfg_path = Path::new(".prompt-lens.yaml");

    if cfg_path.exists() && !force {
        eprintln!("Error: .prompt-lens.yaml already exists. Use --force to overwrite.");
        std::process::exit(1);
    }

    let config = r#"# prompt-lens configuration
# Generated by: prompt-lens init

# Default model for cost calculation
default_model: claude-3-5-sonnet

# Output theme: ansi | nocolor | json
theme: ansi

# Custom optimization rules (optional)
# verbose_phrases:
#   - from: "please kindly"
#     to: "please"

# Suppress warnings for specific patterns (optional)
# ignore_patterns:
#   - "^\\[AUTO-GEN\\]"
"#;

    std::fs::write(cfg_path, config).expect("Failed to write config file");
    println!("[prompt-lens] Config file created: {}", cfg_path.display());
    println!("[prompt-lens] Edit .prompt-lens.yaml to customize settings.");
}

#[allow(dead_code)]
pub fn load_config() -> Option<serde_yaml::Value> {
    load_config_from(Path::new(".prompt-lens.yaml"))
}

pub fn load_config_from(path: &Path) -> Option<serde_yaml::Value> {
    if path.exists() {
        let content = std::fs::read_to_string(path).ok()?;
        serde_yaml::from_str(&content).ok()
    } else {
        None
    }
}

/// Read `default_model` from `.prompt-lens.yaml` in the current directory.
/// Returns `None` if the file is missing, unreadable, malformed, or the
/// key is absent.
pub fn default_model_from_config() -> Option<String> {
    default_model_from_config_path(Path::new(".prompt-lens.yaml"))
}

pub fn default_model_from_config_path(path: &Path) -> Option<String> {
    load_config_from(path)
        .as_ref()
        .and_then(|c| c.get("default_model"))
        .and_then(|v| v.as_str())
        .map(String::from)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::sync::atomic::{AtomicUsize, Ordering};

    // Each test gets its own subdirectory under the temp dir so they can
    // run in parallel without trampling each other's files.
    static COUNTER: AtomicUsize = AtomicUsize::new(0);

    fn write_temp_config(content: &str) -> std::path::PathBuf {
        let n = COUNTER.fetch_add(1, Ordering::SeqCst);
        let dir = std::env::temp_dir().join(format!("prompt-lens-config-test-{n}"));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join(".prompt-lens.yaml");
        fs::write(&path, content).unwrap();
        path
    }

    #[test]
    fn test_default_model_from_config_path_reads_value() {
        let path = write_temp_config("default_model: gpt-4o\n");
        assert_eq!(
            default_model_from_config_path(&path).as_deref(),
            Some("gpt-4o")
        );
    }

    #[test]
    fn test_default_model_from_config_path_missing_key() {
        let path = write_temp_config("theme: ansi\n");
        assert_eq!(default_model_from_config_path(&path), None);
    }

    #[test]
    fn test_default_model_from_config_path_missing_file() {
        let path = std::env::temp_dir()
            .join("prompt-lens-config-test-missing-explicit")
            .join(".prompt-lens.yaml");
        assert_eq!(default_model_from_config_path(&path), None);
    }

    #[test]
    fn test_default_model_from_config_path_malformed_yaml() {
        let path = write_temp_config("default_model: : : not valid yaml\n");
        assert_eq!(default_model_from_config_path(&path), None);
    }
}